# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1299, 832)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.all = QtWidgets.QFrame(self.centralwidget)
        self.all.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.all.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.all.setLineWidth(0)
        self.all.setObjectName("all")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.all)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.upper = QtWidgets.QFrame(self.all)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upper.sizePolicy().hasHeightForWidth())
        self.upper.setSizePolicy(sizePolicy)
        self.upper.setMinimumSize(QtCore.QSize(0, 0))
        self.upper.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.upper.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.upper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upper.setLineWidth(0)
        self.upper.setObjectName("upper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.upper)
        self.verticalLayout_2.setContentsMargins(5, 5, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphsFrame = QtWidgets.QFrame(self.upper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphsFrame.sizePolicy().hasHeightForWidth())
        self.graphsFrame.setSizePolicy(sizePolicy)
        self.graphsFrame.setMinimumSize(QtCore.QSize(806, 321))
        self.graphsFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphsFrame.setLineWidth(0)
        self.graphsFrame.setObjectName("graphsFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.graphsFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graph1Frame = QtWidgets.QFrame(self.graphsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph1Frame.sizePolicy().hasHeightForWidth())
        self.graph1Frame.setSizePolicy(sizePolicy)
        self.graph1Frame.setMinimumSize(QtCore.QSize(390, 301))
        self.graph1Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graph1Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graph1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph1Frame.setLineWidth(0)
        self.graph1Frame.setObjectName("graph1Frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.graph1Frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.graph1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(370, 390))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graph1 = PlotWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph1.sizePolicy().hasHeightForWidth())
        self.graph1.setSizePolicy(sizePolicy)
        self.graph1.setMinimumSize(QtCore.QSize(356, 274))
        self.graph1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graph1.setAutoFillBackground(False)
        self.graph1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"margin: 3px;\n"
"")
        self.graph1.setObjectName("graph1")
        self.horizontalLayout_2.addWidget(self.graph1)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addWidget(self.graph1Frame)
        self.graph2Frame = QtWidgets.QFrame(self.graphsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph2Frame.sizePolicy().hasHeightForWidth())
        self.graph2Frame.setSizePolicy(sizePolicy)
        self.graph2Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graph2Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graph2Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph2Frame.setLineWidth(0)
        self.graph2Frame.setObjectName("graph2Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.graph2Frame)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.graph2Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(370, 390))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_7.setSpacing(3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.graph2 = PlotWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph2.sizePolicy().hasHeightForWidth())
        self.graph2.setSizePolicy(sizePolicy)
        self.graph2.setMinimumSize(QtCore.QSize(356, 274))
        self.graph2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graph2.setAutoFillBackground(False)
        self.graph2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"margin: 3px;\n"
"")
        self.graph2.setObjectName("graph2")
        self.gridLayout_7.addWidget(self.graph2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_4.addWidget(self.graph2Frame)
        self.verticalLayout_2.addWidget(self.graphsFrame)
        self.verticalLayout_3.addWidget(self.upper)
        self.verticalLayout.addWidget(self.all)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"color:rgb(255, 255, 255);\n"
"border-radius:5px;\n"
" border: 2px solid #8e44ad;\n"
"    border-radius: 25px;\n"
"cursor: pointer;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\n"
"    transition: background 0.3s, transform 0.2s;\n"
"height:100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 50, 150);\n"
"transform: scale(1.05);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_5.addWidget(self.browseButton)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.filterButton = QtWidgets.QPushButton(self.frame)
        self.filterButton.setGeometry(QtCore.QRect(30, 0, 561, 101))
        self.filterButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100, 100, 120); /* Grayish-blue background color */\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    border: 2px solid #34495e; /* Contrasting border color (dark gray) */\n"
"    cursor: pointer;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\n"
"    transition: background 0.3s, transform 0.2s;\n"
"    height: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 120); /* Lighter grayish-blue on hover */\n"
"    transform: scale(1.05);\n"
"}\n"
"")
        self.filterButton.setObjectName("filterButton")
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Graph 1"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Graph 2"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.filterButton.setText(_translate("MainWindow", "Filter"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
